### ISSUE TITLE
Modal UX suggestions

### ISSUE THREAD

**Issue by StevenClontz** [lurchmath/lurchmath#1]
![image](https://github.com/lurchmath/lurchmath/assets/1559632/40f9987d-d995-4ff8-bdc2-c39a1c219585)

In this situation, it's unclear what to do. I tried clicking outside the modal to dismiss, and there's no buttons.

I think having "submit" and "cancel" buttons here, with clicking outside the modal being equivalent to "cancel", and submitting the form being equivalent to "submit", would be nice.

**Comment by nathancarter** [comment]
Short answer:  Put your cursor in the dialog and hit Escape.

Long answer:  The problem here is twofold.

 1. We don't have any documentation yet, so you don't have anywhere to go to find out what to do. :)
 2. You are trying out the version of Lurch that is on Ken's server, customized for his students in Spring 2024.  It forces you to use "Advanced mode" editing because that's what Ken plans to teach his students.  The default behavior of the actual app (not the Ken-tweaked-for-his-students copy) is actually "Beginner mode" editing, which is nowhere near as confusing.

To see beginner mode in action, check out the main app page at lurchmath.github.io/lurchmath.

I'm going to close this issue as resolved, because I've given an answer for what to do in that particular situation.  But the more important issue you raise is that we need documentation!  And that issue is DEFINITELY on our to-do list.

**Comment by StevenClontz** [comment]
FWIW I would not consider the issue resolved - I'm suggesting some standard UX patterns that I think would make your app more usable. Best practices >> documentation IMHO.

**Comment by kenmonks** [comment]
Thanks for the feedback.  The problem with that dialog in the Lurch
configuration for my course is not that it's intended to be a non-standard
dialog with no buttons, but rather that it's intended to be a non-dialog
that's currently implemented using a dialog. :)  Eventually I would like
the editing of math expressions to be inline-with-preview (as in apps like
desktop Lurch, Typora, Overleaf's visual editor, etc.).  But we don't have
anything like that built yet, so I'm using the buttonless dialog as a way
to approximate it for the time being (and could improve that approximation
with some css tweaks).

You are right that it's not obvious how to cancel it when the input field
loses focus.  I changed that now on my course website so the expression
editor dialog closes whenever the input field loses focus.  So clicking
outside the model is now equivalent to 'cancel'.  But eventually I would
love to have inline-editing-with-preview instead of that advanced mode
editing dialog.

**Comment by nathancarter** [comment]
Yeah, sorry to have closed the issue prematurely.  Steven, let me ask questions to understand your thoughts better:

Do you think that no dialog like the one you saw should exist, because of the potential confusion it causes, regardless of what documentation/setting hurdles one has to jump through to enable it?

**Comment by StevenClontz** [comment]
I'm simply saying your user interface should incorporate the usual patterns for a modal. See this example https://getbootstrap.com/docs/4.0/components/modal/#live-demo to see how it can be dismissed by clicking outside the modal, or clicking a cancel button, etc.
